Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ItemRazor.Models
{
    public class Item : IComparable<Item>
    {
        [Key] //ikke nødvendig pga conventions 
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int ItemId { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Required]
        public decimal Price { get; set; }

        public Item()
        {
            
        }

        public Item(int id, string name, decimal price)
        {
            ItemId = id;
            Name = name;
            Price = price;
        }

        public int CompareTo(Item other)
        {
            return ItemId - other.ItemId;
        }
    }
}

Pages/Item/CreateItem.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using ItemRazor.Models;
using ItemRazor.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ItemRazor.Pages
{
    public class CreateItemModel : PageModel
    {
        private ItemService itemService;
        private List<Models.Item> items;
       
        [BindProperty]
        public Models.Item Item { get; set; }

        public CreateItemModel(ItemService iS)
        {
            itemService = iS;
            items = itemService.GetItems().ToList();
        }
        public IActionResult OnGet()
        {
            return Page();
        }
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            itemService.AddItem(Item);
            return RedirectToPage("GetAllItems");
        }

    }
}

Pages/Item/DeleteItem.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ItemRazor.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ItemRazor.Pages.Item
{
    public class DeleteItemModel : PageModel
    {
        private ItemService itemService;

        [BindProperty]
        public Models.Item Item { get; set; }

        public DeleteItemModel(ItemService itemService)
        {
            this.itemService = itemService;
        }
        public IActionResult OnGet(int id)
        {
            Item = itemService.GetItem(id);
            if (Item == null)
                return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu

            return Page();
        }

        public IActionResult OnPost(int id)
        {
            Item = itemService.GetItem(id);
            Models.Item deletedItem = itemService.DeleteItem(Item.ItemId);
            if (deletedItem == null)
                return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu
            return RedirectToPage("GetAllItems");
        }
    }
}

Pages/Item/EditItem.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ItemRazor.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ItemRazor.Pages.Item
{
    public class EditItemModel : PageModel
    {
        private ItemService itemService;

        [BindProperty]
        public Models.Item Item { get; set; }

        public EditItemModel(ItemService itemService)
        {
            this.itemService = itemService;
        }
        public IActionResult OnGet(int id)
        {
            Item = itemService.GetItem(id);
            if (Item == null)
                return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu

            return Page();
        }

        public IActionResult OnPost(int id)
        {
            Item = itemService.GetItem(id);
            if (!ModelState.IsValid)
            {
                return Page();
            }
            itemService.UpdateItem(Item);
            return RedirectToPage("GetAllItems");
        }
    }
}

Pages/Item/GelAllItemsAsCards.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ItemRazor.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ItemRazor.Pages.Item
{
    public class GelAllItemsAsCardsModel : PageModel
    {
        private ItemService itemService;
        public List<Models.Item> Items { get; private set; }


        public GelAllItemsAsCardsModel(ItemService itemService)
        {
            this.itemService = itemService;
        }


        public IActionResult OnGet()
        {
            Items = itemService.GetItems().ToList();
            return Page();
        }
    }
}

Pages/Item/GetAllItems.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ItemRazor.Models;
using ItemRazor.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ItemRazor.Pages
{
    public class GetAllItemsModel : PageModel
    {
        private ItemService itemService;
        public List<Models.Item> Items { get; private set; }
        [BindProperty] public string SearchString { get; set; }
        [BindProperty] public int MaxPrice { get; set; }
        [BindProperty] public int MinPrice { get; set; }

        public GetAllItemsModel(ItemService itemService) //Dependency Injection
        {
            this.itemService=itemService;
        }

        public IActionResult OnGet()
        {
            Items = itemService.GetItems().ToList();
            return Page();
        }

        public IActionResult OnGetSortById()
        {
            Items = itemService.SortById().ToList();
            return Page();
        }

        public IActionResult OnGetSortByIdDescending()
        {
            Items = itemService.SortByIdDescending().ToList();
            return Page();
        }

        public IActionResult OnGetSortByName()
        {
            Items = itemService.SortByName().ToList();
            return Page();
        }

        public IActionResult OnGetSortByNameDescending()
        {
            Items = itemService.SortByNameDescending().ToList();
            return Page();
        }

        public IActionResult OnGetSortByPrice()
        {
            Items = itemService.SortByPrice().ToList();
            return Page();
        }

        public IActionResult OnGetSortByPriceDescending()
        {
            Items = itemService.SortByPriceDescending().ToList();
            return Page();
        }

        public IActionResult OnPostNameSearch()
        {
            Items = itemService.NameSearch(SearchString).ToList();
            return Page();
        }

        public IActionResult OnPostPriceFilter(int maxPrice, int minPrice = 0)
        {
            Items = itemService.PriceFilter(maxPrice, minPrice).ToList();
            return Page();
        }
    }
}

Pages/Item/GetAllItemsPagePagination.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ItemRazor.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ItemRazor.Pages.Item
{
    public class GetAllItemsPagePaginationModel : PageModel
    {
        private ItemService itemService;
        public List<Models.Item> Items { get; private set; }
        [BindProperty] public string SearchString { get; set; }
        [BindProperty] public int MaxPrice { get; set; }
        [BindProperty] public int MinPrice { get; set; }

        //Page pagination:
        [BindProperty(SupportsGet = true)] public int CurrentPage { get; set; } = 1;
        public int Count { get; set; }
        public int PageSize { get; set; } = 10;
        public int TotalPages => (int)Math.Ceiling(decimal.Divide(Count, PageSize));





        public GetAllItemsPagePaginationModel(ItemService itemService) //Dependency Injection
        {
            this.itemService = itemService;
        }

        //public IActionResult OnGet()
        //{
        //    Items = itemService.GetItems().ToList();
        //    return Page();
        //}

        public IActionResult OnGetSortById()
        {
            Items = itemService.SortById().ToList();
            return Page();
        }

        public IActionResult OnGetSortByIdDescending()
        {
            Items = itemService.SortByIdDescending().ToList();
            return Page();
        }

        public IActionResult OnGetSortByName()
        {
            Items = itemService.SortByName().ToList();
            return Page();
        }

        public IActionResult OnGetSortByNameDescending()
        {
            Items = itemService.SortByNameDescending().ToList();
            return Page();
        }

        public IActionResult OnGetSortByPrice()
        {
            Items = itemService.SortByPrice().ToList();
            return Page();
        }

        public IActionResult OnGetSortByPriceDescending()
        {
            Items = itemService.SortByPriceDescending().ToList();
            return Page();
        }


        public IActionResult OnPostNameSearch()
        {
            Items = itemService.NameSearch(SearchString).ToList();
            return Page();
        }

        public IActionResult OnPostPriceFilter(int maxPrice, int minPrice = 0)
        {
            Items = itemService.PriceFilter(maxPrice, minPrice).ToList();
            return Page();
        }


        //Page pagination
        public bool ShowPrevious => CurrentPage > 1;
        public bool ShowNext => CurrentPage < TotalPages;
        public bool ShowFirst => CurrentPage != 1;
        public bool ShowLast => CurrentPage != TotalPages;

        public async Task OnGetAsync()
        {
            Items = await itemService.GetPaginatedResult(CurrentPage, PageSize);
            Count = await itemService.GetCount();
        }
    }

}

Pages/Item/CreateItem.cshtml
@page
@model ItemRazor.Pages.CreateItemModel
@{
}

<h1>Create a new Computer Item</h1>

<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div class="form-group">
                <label asp-for="@Model.Item.ItemId" class="control-lable"></label>
                <input asp-for="@Model.Item.ItemId" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Item.Name" class="control-lable"></label>
                <input asp-for="@Model.Item.Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Item.Price" class="control-lable"></label>
                <input asp-for="@Model.Item.Price" class="form-control" />
                
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-page="/Item/GetAllItems">Back to List</a>
</div>

Pages/Item/DeleteItem.cshtml
@page "{id:int}"
@model ItemRazor.Pages.Item.DeleteItemModel
@{
}
<h1>Delete Confirmation</h1>
<div class="alert alert-danger">
    <h5>Are you sure you want to delete Item - @Model.Item.Name</h5>
    <form method="post">
        <button type="submit" class="btn btn-danger">Yes</button>
        <a class="btn btn-primary" asp-page="/Item/GetAllItems">No</a>
    </form>
</div>

Pages/Item/EditItem.cshtml
@page "{id:int}"
@model ItemRazor.Pages.Item.EditItemModel
@{
}

<h1>EditEvent</h1>

<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div class="form-group">
                <label asp-for="@Model.Item.ItemId" class="control-lable"></label>
                <input asp-for="@Model.Item.ItemId" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Item.Name" class="control-lable"></label>
                <input asp-for="@Model.Item.Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Item.Price" class="control-lable"></label>
                <input asp-for="@Model.Item.Price" class="form-control" />

            </div>

            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-page="/Item/GetAllItems">Back to List</a>
</div>

Pages/Item/GelAllItemsAsCards.cshtml
@page "{handler?}"
@model ItemRazor.Pages.Item.GelAllItemsAsCardsModel
@{
}
<div class="container-fluid pt-3">
<h3 class="font-weight-light text-white">Kanban Board</h3>
<div class="small  text-light">Drag and drop between swim lanes</div>

<div class="row flex-row flex-sm-nowrap py-3">
    <div class="col-3">
        <div class="card bg-light">
            <div class="card-body">
                <h6 class="card-title text-uppercase text-truncate py-2">To Do</h6>
                <div class="items border border-light">
                    @if (@Model.Items != null)
                    {
                        foreach (var item in Model.Items)
                        {
                            <div class="card-body p-2">
                                <div class="card-title">
                                    @item.Name
                                </div>
                                <p>Navn: @item.Name Pris: @item.Price</p>
                            </div>

                        }
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="col-3">
        <div class="card bg-light">
            <div class="card-body">
                <h6 class="card-title text-uppercase text-truncate py-2">Doing</h6>
                <div class="items border border-light">
                    @if (@Model.Items != null)
                    {
                        foreach (var item in Model.Items)
                        {
                            <div class="card-body p-2">
                                <div class="card-title">
                                    @item.Name
                                </div>
                                <p>Navn: @item.Name Pris: @item.Price</p>
                            </div>

                        }
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-light">
            <div class="card-body">
                <h6 class="card-title text-uppercase text-truncate py-2">Done</h6>
                <div class="items border border-light">
                    @if (@Model.Items != null)
                    {
                        foreach (var item in Model.Items)
                        {
                            <div class="card-body p-2">
                                <div class="card-title">
                                    @item.Name
                                </div>
                                <p>Navn: @item.Name Pris: @item.Price</p>
                            </div>

                        }
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div class="card bg-light">
            <div class="card-body">
                <h6 class="card-title text-uppercase text-truncate py-2">Done Done</h6>
                <div class="items border border-light">
                    @if (@Model.Items != null)
                    {
                        foreach (var item in Model.Items)
                        {
                            <div class="card-body p-2">
                                <div class="card-title">
                                    @item.Name
                                </div>
                                <p>Navn: @item.Name Pris: @item.Price</p>
                            </div>

                        }
                    }
                </div>
            </div>
        </div>
    </div>
</div>
</div>

Pages/Item/GetAllItems.cshtml
@page 
@model ItemRazor.Pages.GetAllItemsModel
@{
}
<br />
<h1>Computer Items</h1>
<br />
<div class="row">
        <div class="col-4"><h5>Search Name</h5></div>
        <div class="col-4"><h5>Filter Price</h5></div>
        <div class="col-4"></div>
</div>
<div class="row">
    <div class="col-4">
        <form method="post" class="form-inline">
            <input asp-for="@Model.SearchString" class="form-control mr-1" placeholder="Enter search term"/>
            <input type="submit" asp-page-handler="NameSearch" value="Search" class="btn btn-primary"/>
        </form>
    </div>
        
<div class="col-5">
    <form method="post" class="form-inline">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">Min</span>
            </div>
            <input asp-for="@Model.MinPrice" class="form-control mr-1"/>
        
            <div class="input-group-prepend">
                <span class="input-group-text">Max</span>
            </div>
            <input asp-for="@Model.MaxPrice" class="form-control mr-1"/>
            <input type="submit" asp-page-handler="PriceFilter" value="Filter" class="btn btn-primary" />
        </div>
    </form>
</div>

<div class="col-2"></div>
</div>    
<br/>
<div class="test">
    <table class="table table-bordered table-hover table-striped" width="60%">
        <col style="width: 7%">
        <col style="width: 70%">
        <col style="width: 9%">
        <col style="width: 14%">
        <thead>
            <tr class="btn-secondary active">
                <th>
                    <div class="d-flex justify-content-between p-0">
                        <div><h5>Id </h5></div>
                        <div>
                        <a data-toggle="tooltip" title="Sort By Id" asp-page-handler="SortById"><i class="fa fa-angle-up"></i></a>
                            <a data-toggle="tooltip" title="Sort By Id Descending" asp-page-handler="SortByIdDescending"><i class="fa fa-angle-down"></i></a>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="d-flex justify-content-between p-0">
                        <div>
                            <h5>Name </h5>
                        </div>
                        <div>
                            <a data-toggle="tooltip" title="Sort By Name" asp-page-handler="SortByName"><i class="fa fa-angle-up"></i></a>
                            <a data-toggle="tooltip" title="Sort By Name Descending" asp-page-handler="SortByNameDescending"><i class="fa fa-angle-down"></i></a>
                        </div>
                    </div>
                   
                </th>
                <th>
                    <div class="d-flex justify-content-between p-0">
                        <div>
                            <h5>Price </h5>
                        </div>
                        <div>
                            <a data-toggle="tooltip" title="Sort By Price" asp-page-handler="SortByPrice"><i class="fa fa-angle-up"></i></a>
                            <a data-toggle="tooltip" title="Sort By Price Descending" asp-page-handler="SortByPriceDescending"><i class="fa fa-angle-down"></i></a>
                        </div>
                    </div>
                </th>
                <th>
                    <h5>Action</h5>
                </th>
            </tr>
        </thead>
        <tbody>
            @if (@Model.Items != null)
            {
                foreach (var item in Model.Items)
                {
                    <tr class="btn-secondary">
                        <td>
                            @item.ItemId
                        </td>
                        <td>
                            @item.Name
                        </td>
                        <td>
                            @item.Price
                        </td>
                        <td>
                            <!-- Call to action buttons -->
                            <ul class="list-inline m-0">
                                <li class="list-inline-item">
                                    <a class="btn btn-primary btn-sm" type="button" data-toggle="tooltip" title="Edit" asp-page="EditItem" asp-route-id="@item.ItemId"><i class="fa fa-edit"></i></a>
                                </li>
                                <li class="list-inline-item">
                                    <a class="btn btn-danger btn-sm " type="button" data-toggle="tooltip" data-placement="top" title="Delete" asp-page="DeleteItem" asp-route-id="@item.ItemId"><i class="fa fa-trash"></i></a>
                                </li>
                                <li class="list-inline-item">
                                    <a class="btn btn-primary btn-sm " type="button" data-toggle="tooltip" data-placement="top" title="Order" asp-page="../Order/OrderItem" asp-route-id="@item.ItemId"><i class="fa fa-shopping-cart"></i></a>
                                </li>
                            </ul>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<br />
<p>
    <a class="btn btn-primary" data-toggle="tooltip" title="Add Item" asp-page="CreateItem"><i class="fa fa-plus-square mr-1"></i> Create a new Item </a>
</p>
<br/>

Pages/Item/GetAllItemsPagePagination.cshtml
@page "{handler?}"
@model ItemRazor.Pages.Item.GetAllItemsPagePaginationModel
@{
}
<br />
<h1>Computer Items</h1>
<br />
<div class="row">
    <div class="col-4"><h5>Search Name</h5></div>
    <div class="col-4"><h5>Filter Price</h5></div>
    <div class="col-4"></div>
</div>
<div class="row">
    <div class="col-4">
        <form method="post" class="form-inline">
            <input asp-for="@Model.SearchString" class="form-control mr-1" placeholder="Enter search term" />
            <input type="submit" asp-page-handler="NameSearch" value="Search" class="btn btn-primary" />
        </form>
    </div>

    <div class="col-5">
        <form method="post" class="form-inline">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">Min</span>
                </div>
                <input asp-for="@Model.MinPrice" class="form-control mr-1" />

                <div class="input-group-prepend">
                    <span class="input-group-text">Max</span>
                </div>
                <input asp-for="@Model.MaxPrice" class="form-control mr-1" />
                <input type="submit" asp-page-handler="PriceFilter" value="Filter" class="btn btn-primary" />
            </div>
        </form>
    </div>

    <div class="col-2"></div>
</div>
<br />
<div class="test">
    <table class="table table-bordered table-hover table-striped" width="60%">
        <col style="width: 7%">
        <col style="width: 74%">
        <col style="width: 10%">
        <col style="width: 9%">
        <thead>
            <tr class="btn-secondary active">
                <th>
                    <div class="d-flex justify-content-between p-0">
                        <div><h5>Id </h5></div>
                        <div>
                            <a data-toggle="tooltip" title="Sort By Id" asp-page-handler="SortById"><i class="fa fa-angle-up"></i></a>
                            <a data-toggle="tooltip" title="Sort By Id Descending" asp-page-handler="SortByIdDescending"><i class="fa fa-angle-down"></i></a>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="d-flex justify-content-between p-0">
                        <div>
                            <h5>Name </h5>
                        </div>
                        <div>
                            <a data-toggle="tooltip" title="Sort By Name" asp-page-handler="SortByName"><i class="fa fa-angle-up"></i></a>
                            <a data-toggle="tooltip" title="Sort By Name Descending" asp-page-handler="SortByNameDescending"><i class="fa fa-angle-down"></i></a>
                        </div>
                    </div>
                   
                </th>
                <th>
                    <div class="d-flex justify-content-between p-0">
                        <div>
                            <h5>Price </h5>
                        </div>
                        <div>
                            <a data-toggle="tooltip" title="Sort By Price" asp-page-handler="SortByPrice"><i class="fa fa-angle-up"></i></a>
                            <a data-toggle="tooltip" title="Sort By Price Descending" asp-page-handler="SortByPriceDescending"><i class="fa fa-angle-down"></i></a>
                        </div>
                    </div>
                </th>
                <th>
                    <h5>Action</h5>
                </th>
            </tr>
        </thead>
        <tbody>
            @if (@Model.Items != null)
            {
                foreach (var item in Model.Items)
                {
                    <tr class="btn-secondary">
                        <td>
                            @item.ItemId
                        </td>
                        <td>
                            @item.Name
                        </td>
                        <td>
                            @item.Price
                        </td>
                        <td>
                            <!-- Call to action buttons -->
                            <ul class="list-inline m-0">
                                <li class="list-inline-item">
                                    <a class="btn btn-primary btn-sm" type="button" data-toggle="tooltip" title="Edit" asp-page="EditItem" asp-route-id="@item.ItemId"><i class="fa fa-edit"></i></a>
                                </li>
                                <li class="list-inline-item">
                                    <a class="btn btn-danger btn-sm " type="button" data-toggle="tooltip" data-placement="top" title="Delete" asp-page="DeleteItem" asp-route-id="@item.ItemId"><i class="fa fa-trash"></i></a>
                                </li>
                            </ul>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<div>
    <ul class="pagination">
        <li class="page-item @(!Model.ShowFirst? "disabled":"")">
            <a asp-page="GetAllItemsPagePagination" asp-route-CurrentPage="1" class="page-link"> <i class="fa fa-fast-backward"></i></a>
        </li>

        <li class="page-item @(!Model.ShowPrevious? "disabled":"")">
            <a asp-page="GetAllItemsPagePagination" asp-route-CurrentPage="@(Model.CurrentPage -1)" class="page-link"><i class="fa fa-angle-left"></i></a>
        </li>
        <li class="page-item  @(!Model.ShowNext? "disabled":"")">
            <a asp-page="GetAllItemsPagePagination" asp-route-CurrentPage="@(Model.CurrentPage + 1)" class="page-link"><i class="fa fa-angle-right"></i></a>
        </li>

        <li class="page-item  @(!Model.ShowLast? "disabled":"")">
            <a asp-page="GetAllItemsPagePagination" asp-route-CurrentPage="@Model.TotalPages" class="page-link"><i class="fa fa-fast-forward"></i></a>
        </li>
        <li class="page-item ml-2">
            <a class="page-link">@Model.CurrentPage</a>
        </li>
        <li class="page-item">
            <a class="page-link">of</a>
        </li>
        <li class="page-item">
            <a class="page-link">@Model.TotalPages pages</a>
        </li>
    </ul>
</div>

<br />
<p>
    <a class="btn btn-primary" data-toggle="tooltip" title="Add Item" asp-page="CreateItem"><i class="fa fa-plus-square mr-1"></i> Create a new Item </a>
</p>
<br />